### PR TITLE
Replaced the FABRIC_NODE_ID by FABRIC_GROUP_ID for Sforza

### PR DESCRIPTION
**Pull request by HankChang**
Signed-off-by: Hank Chang <chhank@tw.ibm.com>

### CODE REVIEW

**Comment by dcrowell77** [comment]
I'm not opposed to this, but there is downstream code that probably needs to be changed before this can go in.
@pragupta @rubymart @a-barrera @bwmashak

**Comment by pragupta** [comment]
I have a gerrit commit to remove it from attribute_types/target_types and rest of the code. Once it goes in, we can push it github. and update our xmls

**Comment by pragupta** [comment]
Changes to target_types/attributes_types are now merged as part of #66

**Comment by pragupta** [comment]
looks like this changes has been merged already via a different pull request. I am closing this.

**Pull request closed without merging**
