### PR TITLE
Created new master-p8 branch

### PR DESCRIPTION
**Pull request by ruby452**
To keep attribute_types.xml file unique to P8 separate from those of P9.

### CODE REVIEW

**Comment by williamspatrick** [comment]
The title of this is not what the pull request is doing. It is making changes to the master branch. 

@spinler - Do we want separate branches for this?  I thought we were trying to keep things common.

**Comment by dcrowell77** [comment]
@ruby452 and @nkskjames chatted with me today.  Ruby discovered that the code can't handle the attribute split that we've got in Hostboot for P8/P9 so Norm thought branching was the simplest solution.

**Comment by spinler** [comment]
@williamspatrick This should be OK for OpenBMC.  We never fetch this repository, only the repository for the XML that was generated using this metadata.

**Comment by williamspatrick** [comment]
@ruby452 - I created a branch titled 'master-p8' now within this repository.  You will need to recreate the pull request to put that branch as your destination before this can be merged.

**Pull request closed without merging**
